---
- name: Configure Controller Node
  hosts: all
  become: yes

  tasks:
    - name: Install NTP package
      apt:
        name: chrony
        state: present

    - name: Configure NTP servers
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^pool '
        line: "pool {{ item }}"
        state: present
      with_items:
        - 0.ubuntu.pool.ntp.org
        - 1.ubuntu.pool.ntp.org

    - name: Restart NTP service
      service:
        name: chrony
        state: restarted
        enabled: yes

    - name: Add OpenStack Zed repository using cloud-archive
      command: "add-apt-repository -y cloud-archive:zed"

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenStack client and prerequisites
      apt:
        name:
          - software-properties-common
          - python3-openstackclient
          - python3-pip
        state: present

    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present

    - name: Configure MySQL root password
      debconf:
        name: mariadb-server
        question: "mysql-server/root_password"
        value: "4704"
        vtype: "password"

    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted
        enabled: yes

    - name: Install RabbitMQ
      apt:
        name: rabbitmq-server
        state: present

    - name: Set RabbitMQ user password
      command: "rabbitmqctl change_password guest 4704"

    - name: Install memcached
      apt:
        name: memcached
        state: present

    - name: Configure memcached IP
      lineinfile:
        path: /etc/memcached.conf
        regexp: '-l 127.0.0.1'
        line: "-l 127.0.0.1"

    - name: Restart memcached
      service:
        name: memcached
        state: restarted
        enabled: yes

    - name: Install etcd
      apt:
        name: etcd
        state: present

    - name: Configure etcd
      copy:
        dest: /etc/default/etcd
        content: |
          ETCD_LISTEN_PEER_URLS="http://127.0.0.1:2380"
          ETCD_LISTEN_CLIENT_URLS="http://127.0.0.1:2379"
          ETCD_INITIAL_ADVERTISE_PEER_URLS="http://127.0.0.1:2380"
          ETCD_INITIAL_CLUSTER="controller=http://127.0.0.1:2380"
          ETCD_INITIAL_CLUSTER_TOKEN="my_etcd_cluster"
          ETCD_INITIAL_CLUSTER_STATE="new"
          ETCD_ADVERTISE_CLIENT_URLS="http://127.0.0.1:2379"

    - name: Restart etcd
      service:
        name: etcd
        state: restarted
        enabled: yes

- name: Configure Compute Node
  hosts: all
  become: yes

  tasks:
    - name: Refresh the apt cache
      apt:
        update_cache: yes
